"""
Fill Polygon Gaps - QGIS Processing Script
============================================
Fills gaps between a selected polygon and its neighbors within a 
user-defined extent. Supports preview-before-apply workflow.

How to install:
  1. Open QGIS
  2. Go to Processing Toolbox > Scripts > Add Script to Toolbox...
  3. Select this file
  4. The tool appears under "Polygon Tools > Fill Polygon Gaps"

Author: Generated by Antigravity AI
"""

from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingParameterVectorLayer,
    QgsProcessingParameterExtent,
    QgsProcessingParameterEnum,
    QgsProcessingParameterField,
    QgsProcessingParameterString,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterFeatureSink,
    QgsProcessingException,
    QgsProcessingUtils,
    QgsFeature,
    QgsFeatureRequest,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsRectangle,
    QgsWkbTypes,
    QgsSymbol,
    QgsRendererCategory,
    QgsCategorizedSymbolRenderer,
    QgsSingleSymbolRenderer,
    QgsProject,
    QgsMapLayer,
)
from qgis.PyQt.QtCore import QVariant
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtWidgets import QComboBox
from qgis.analysis import QgsGeometrySnapper
from processing.gui.wrappers import WidgetWrapper


class FeatureValueWidgetWrapper(WidgetWrapper):
    """
    Custom widget wrapper for the polygon identifier value parameter.
    Dynamically populates a QComboBox with unique values from the chosen
    field of the selected input layer. If an extent is defined (either manual
    or via extent layer), only values/FIDs from features intersecting the
    combined extent are listed.
    """
    def createWidget(self):
        self.combo = QComboBox()
        self.combo.setEditable(True)  # Allow typing custom/manually entered values
        self.combo.currentTextChanged.connect(self.on_combo_changed)
        
        self.layer_wrapper = None
        self.field_wrapper = None
        self.extent_mode_wrapper = None
        self.extent_wrapper = None
        self.extent_layer_wrapper = None
        return self.combo

    def postInitialize(self, wrappers):
        # Locate the parent wrappers to listen to their updates
        for w in wrappers:
            name = w.parameterDefinition().name()
            if name == 'INPUT_LAYER':
                self.layer_wrapper = w
                w.widgetValueHasChanged.connect(self.on_parent_changed)
            elif name == 'LABEL_FIELD':
                self.field_wrapper = w
                w.widgetValueHasChanged.connect(self.on_parent_changed)
            elif name == 'EXTENT_MODE':
                self.extent_mode_wrapper = w
                w.widgetValueHasChanged.connect(self.on_parent_changed)
            elif name == 'EXTENT':
                self.extent_wrapper = w
                w.widgetValueHasChanged.connect(self.on_parent_changed)
            elif name == 'EXTENT_LAYER':
                self.extent_layer_wrapper = w
                w.widgetValueHasChanged.connect(self.on_parent_changed)
        
        # Initial population of options
        self.on_parent_changed()

    def on_combo_changed(self, text):
        self.widgetValueHasChanged.emit(self)

    def on_parent_changed(self):
        if not self.layer_wrapper:
            return
        
        # Use widgetValue() instead of value() to avoid AttributeError
        layer_val = self.layer_wrapper.widgetValue()
        layer = None
        
        if isinstance(layer_val, QgsMapLayer):
            layer = layer_val
        elif isinstance(layer_val, str) and layer_val:
            layer = QgsProject.instance().mapLayer(layer_val)
            if not layer:
                layers = QgsProject.instance().mapLayersByName(layer_val)
                if layers:
                    layer = layers[0]
        
        if not layer:
            self.combo.clear()
            return
            
        field_name = self.field_wrapper.widgetValue() if self.field_wrapper else ''
        
        # Determine the selected extent mode
        extent_mode = 0
        if self.extent_mode_wrapper:
            try:
                val = self.extent_mode_wrapper.widgetValue()
                if isinstance(val, int):
                    extent_mode = val
                else:
                    val_str = str(val).lower()
                    if 'layer' in val_str:
                        extent_mode = 1
                    else:
                        extent_mode = 0
            except Exception:
                pass

        extent_rect = None
        
        if extent_mode == 0:
            # Mode 0: Manual Extent
            if self.extent_wrapper:
                extent_val = self.extent_wrapper.widgetValue()
                if isinstance(extent_val, QgsRectangle):
                    extent_rect = extent_val
                elif isinstance(extent_val, str) and extent_val:
                    try:
                        rect_res = QgsProcessingUtils.stringToRectangle(extent_val)
                        if rect_res and len(rect_res) > 0:
                            extent_rect = rect_res[0]
                    except Exception:
                        pass
        else:
            # Mode 1: Extent Layer
            if self.extent_layer_wrapper:
                layer_val = self.extent_layer_wrapper.widgetValue()
                ext_layer = None
                if isinstance(layer_val, QgsMapLayer):
                    ext_layer = layer_val
                elif isinstance(layer_val, str) and layer_val:
                    ext_layer = QgsProject.instance().mapLayer(layer_val)
                    if not ext_layer:
                        layers = QgsProject.instance().mapLayersByName(layer_val)
                        if layers:
                            ext_layer = layers[0]
                if ext_layer:
                    combined = QgsRectangle()
                    for f in ext_layer.getFeatures():
                        geom = f.geometry()
                        if geom and not geom.isEmpty():
                            combined.combineExtentWith(geom.boundingBox())
                    if not combined.isEmpty():
                        extent_rect = combined

        request = QgsFeatureRequest()
        if extent_rect and not extent_rect.isEmpty():
            request.setFilterRect(extent_rect)

        # Block signals to avoid infinite recursion while repopulating
        self.combo.blockSignals(True)
        current_text = self.combo.currentText()
        self.combo.clear()
        
        items = []
        if field_name:
            field_idx = layer.fields().indexOf(field_name)
            if field_idx >= 0:
                if extent_rect and not extent_rect.isEmpty():
                    # Filter unique values only to features intersecting the extent
                    unique_vals = set()
                    # Optimize: only fetch the needed field
                    request.setSubsetOfAttributes([field_name], layer.fields())
                    for feat in layer.getFeatures(request):
                        val = feat[field_name]
                        if val is not None and str(val).strip():
                            unique_vals.add(str(val).strip())
                    items = sorted(list(unique_vals))
                else:
                    # Fallback to all unique values in the entire layer
                    unique_vals = layer.uniqueValues(field_idx)
                    items = sorted([
                        str(v).strip() for v in unique_vals 
                        if v is not None and str(v).strip()
                    ])
        else:
            # Fallback to listing Feature IDs (FIDs) intersecting the extent
            # Optimize: do not fetch any attributes when getting FIDs
            request.setNoAttributes()
            items = [str(f.id()) for f in layer.getFeatures(request)]
            if len(items) > 1000:
                items = items[:1000]
                
        self.combo.addItems(items)
        
        # Restore previous value if it's still available in the new items list
        idx = self.combo.findText(current_text)
        if idx >= 0:
            self.combo.setCurrentIndex(idx)
        elif items:
            self.combo.setCurrentIndex(0)
            
        self.combo.blockSignals(False)
        self.widgetValueHasChanged.emit(self)

    def value(self):
        return self.combo.currentText()

    def setValue(self, value):
        self.combo.blockSignals(True)
        idx = self.combo.findText(str(value))
        if idx >= 0:
            self.combo.setCurrentIndex(idx)
        else:
            self.combo.setEditText(str(value))
        self.combo.blockSignals(False)

    # Overrides for newer QGIS 3 APIs
    def widgetValue(self):
        return self.combo.currentText()

    def setWidgetValue(self, value, context):
        self.combo.blockSignals(True)
        idx = self.combo.findText(str(value))
        if idx >= 0:
            self.combo.setCurrentIndex(idx)
        else:
            self.combo.setEditText(str(value))
        self.combo.blockSignals(False)



class ExtentModeWidgetWrapper(WidgetWrapper):
    """
    Custom widget wrapper for the extent processing mode dropdown.
    Dynamically toggles the visibility of the 'EXTENT' and 'EXTENT_LAYER' parameters.
    """
    def createWidget(self):
        self.combo = QComboBox()
        self.combo.addItems([
            'Working Extent (Single Rectangular Box)',
            'Extent Layer (Multiple Custom Polygons)'
        ])
        self.combo.currentIndexChanged.connect(self.on_mode_changed)
        self.extent_wrapper = None
        self.extent_layer_wrapper = None
        return self.combo

    def postInitialize(self, wrappers):
        for w in wrappers:
            name = w.parameterDefinition().name()
            if name == 'EXTENT':
                self.extent_wrapper = w
            elif name == 'EXTENT_LAYER':
                self.extent_layer_wrapper = w
        # Initialize visibility based on the current selection
        self.on_mode_changed(self.combo.currentIndex())

    def on_mode_changed(self, index):
        if self.extent_wrapper:
            try:
                widget = self.extent_wrapper.wrappedWidget()
                if widget:
                    widget.setVisible(index == 0)
            except AttributeError:
                pass
            try:
                label = self.extent_wrapper.wrappedLabel()
                if label:
                    label.setVisible(index == 0)
            except AttributeError:
                pass

        if self.extent_layer_wrapper:
            try:
                widget = self.extent_layer_wrapper.wrappedWidget()
                if widget:
                    widget.setVisible(index == 1)
            except AttributeError:
                pass
            try:
                label = self.extent_layer_wrapper.wrappedLabel()
                if label:
                    label.setVisible(index == 1)
            except AttributeError:
                pass

        self.widgetValueHasChanged.emit(self)

    def value(self):
        return self.combo.currentIndex()

    def setValue(self, value):
        try:
            self.combo.setCurrentIndex(int(value))
        except Exception:
            pass

    def widgetValue(self):
        return self.combo.currentIndex()

    def setWidgetValue(self, value, context):
        try:
            self.combo.setCurrentIndex(int(value))
        except Exception:
            pass


class FillPolygonGapsAlgorithm(QgsProcessingAlgorithm):

    # Parameter names
    INPUT_LAYER = 'INPUT_LAYER'
    EXTENT_MODE = 'EXTENT_MODE'
    EXTENT = 'EXTENT'
    EXTENT_LAYER = 'EXTENT_LAYER'
    LABEL_FIELD = 'LABEL_FIELD'
    FEATURE_VALUE = 'FEATURE_VALUE'
    APPLY_CHANGES = 'APPLY_CHANGES'
    OUTPUT_PREVIEW = 'OUTPUT_PREVIEW'

    def name(self):
        return 'fillpolygongaps'

    def displayName(self):
        return 'Fill Polygon Gaps'

    def group(self) -> str:
        """
        Returns the name of the group this algorithm belongs to.
        """
        return "GMD Toolkits"

    def groupId(self) -> str:
        """
        Returns the unique ID of the group this algorithm belongs to.
        """
        return "gmdtoolkits"

    def tags(self):
        return ['polygon', 'gap', 'fill', 'topology', 'snap', 'fix']

    def shortHelpString(self):
        return (
            "<b>Fill Polygon Gaps</b><br><br>"
            "Fills gaps between a selected polygon and its neighbors "
            "within a user-defined extent, without creating overlaps.<br><br>"
            "<b>Workflow:</b><br>"
            "1. Select the polygon layer<br>"
            "2. Select the extent processing mode (dropdown) and define the chosen extent parameter<br>"
            "3. Choose a field to identify polygons (optional — uses FID if empty)<br>"
            "4. Enter/select the value to identify the target polygon from the dropdown<br>"
            "5. <b>Uncheck</b> 'Apply changes' to preview first<br>"
            "6. Inspect the preview layer (3 categories: original, gap, result)<br>"
            "7. If satisfied, re-run with 'Apply changes' <b>checked</b><br><br>"
            "<b>Preview layer categories:</b><br>"
            "• <span style='color:#3498db'>■</span> <b>original</b> — "
            "the polygon before changes<br>"
            "• <span style='color:#e74c3c'>■</span> <b>gap_fill</b> — "
            "the gap area that will be added<br>"
            "• <span style='color:#2ecc71'>■</span> <b>result</b> — "
            "the polygon after gap filling<br>"
        )

    def createInstance(self):
        return FillPolygonGapsAlgorithm()

    # =========================================================================
    #  PARAMETERS
    # =========================================================================

    def initAlgorithm(self, config=None):
        # 1 ── Input polygon layer
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.INPUT_LAYER,
                'Input Polygon Layer',
                [QgsProcessing.TypeVectorPolygon],
            )
        )

        # 2 ── Extent processing mode dropdown
        extent_mode_param = QgsProcessingParameterEnum(
            self.EXTENT_MODE,
            'Extent processing mode',
            options=[
                'Working Extent (Single Rectangular Box)',
                'Extent Layer (Multiple Custom Polygons)'
            ],
            allowMultiple=False,
            defaultValue=0
        )
        extent_mode_param.setMetadata({
            'widget_wrapper': {'class': ExtentModeWidgetWrapper}
        })
        self.addParameter(extent_mode_param)

        # 2a ── Working extent
        self.addParameter(
            QgsProcessingParameterExtent(
                self.EXTENT,
                'Working Extent (required if mode is Working Extent) [optional]',
                optional=True,
            )
        )

        # 2b ── Extent layer
        self.addParameter(
            QgsProcessingParameterVectorLayer(
                self.EXTENT_LAYER,
                'Extent Layer (required if mode is Extent Layer) [optional]',
                [QgsProcessing.TypeVectorPolygon],
                optional=True,
            )
        )

        # 3 ── Field to identify polygons (optional)
        #      This dropdown auto-populates from the selected layer.
        #      If left empty, FID is used instead.
        self.addParameter(
            QgsProcessingParameterField(
                self.LABEL_FIELD,
                'Field to identify polygons (leave empty to use FID)',
                parentLayerParameterName=self.INPUT_LAYER,
                optional=True,
            )
        )

        # 4 ── Value to match in the chosen field (or FID number)
        feature_value_param = QgsProcessingParameterString(
            self.FEATURE_VALUE,
            'Polygon identifier value (field value or FID number)',
            optional=False,
        )
        feature_value_param.setMetadata({
            'widget_wrapper': {'class': FeatureValueWidgetWrapper}
        })
        self.addParameter(feature_value_param)

        # 5 ── Apply changes toggle
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.APPLY_CHANGES,
                'Apply changes to source layer (uncheck for preview only)',
                defaultValue=False,
            )
        )

        # 6 ── Preview output sink
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_PREVIEW,
                'Preview Output',
                QgsProcessing.TypeVectorPolygon,
            )
        )

    # =========================================================================
    #  ALGORITHM
    # =========================================================================

    def processAlgorithm(self, parameters, context, feedback):
        # ── Read parameters ──────────────────────────────────────────────────
        layer = self.parameterAsVectorLayer(
            parameters, self.INPUT_LAYER, context
        )
        
        # Read extent mode dropdown index
        extent_mode = self.parameterAsEnum(
            parameters, self.EXTENT_MODE, context
        )

        label_field = self.parameterAsString(
            parameters, self.LABEL_FIELD, context
        ).strip()
        feature_value = self.parameterAsString(
            parameters, self.FEATURE_VALUE, context
        ).strip()
        apply_changes = self.parameterAsBool(
            parameters, self.APPLY_CHANGES, context
        )

        # ── Validate inputs ─────────────────────────────────────────────────
        if not layer or not layer.isValid():
            raise QgsProcessingException("Invalid input layer.")

        extent_geoms = []

        if extent_mode == 0:
            # Mode 0: Manual extent
            extent_rect = None
            try:
                extent_rect = self.parameterAsExtent(
                    parameters, self.EXTENT, context, layer.crs()
                )
            except Exception:
                pass
            if not extent_rect or extent_rect.isEmpty():
                raise QgsProcessingException(
                    "Working Extent is required when 'Working Extent' processing mode is selected."
                )
            extent_geoms.append(QgsGeometry.fromRect(extent_rect))
        else:
            # Mode 1: Extent layer
            extent_layer = self.parameterAsVectorLayer(
                parameters, self.EXTENT_LAYER, context
            )
            if not extent_layer or not extent_layer.isValid():
                raise QgsProcessingException(
                    "Extent Layer is required when 'Extent Layer' processing mode is selected."
                )
            for feat in extent_layer.getFeatures():
                geom = feat.geometry()
                if geom and not geom.isEmpty():
                    extent_geoms.append(geom)

        if not extent_geoms:
            raise QgsProcessingException("No valid extent geometries found to process.")

        # Compute combined bounding box for target feature lookup
        combined_bbox = QgsRectangle()
        for geom in extent_geoms:
            combined_bbox.combineExtentWith(geom.boundingBox())

        feedback.pushInfo(
            f"━━━ Fill Polygon Gaps ━━━\n"
            f"Layer       : {layer.name()} ({layer.featureCount()} features)\n"
            f"Extents     : {len(extent_geoms)} area(s) to process\n"
            f"Identify by : {'field «' + label_field + '»' if label_field else 'FID'}\n"
            f"Value       : {feature_value}\n"
            f"Apply       : {'YES — will modify source' if apply_changes else 'NO — preview only'}\n"
        )

        # ── Step 1: Find target feature ──────────────────────────────────────
        feedback.setProgressText("Step 1/5: Finding target feature...")
        feedback.setProgress(0)

        target_feature = self._find_target_feature(
            layer, combined_bbox, label_field, feature_value, feedback
        )

        target_geom = target_feature.geometry()
        
        # Verify target intersects at least one of the active extents
        intersects_any = False
        for ext_geom in extent_geoms:
            if target_geom.intersects(ext_geom):
                intersects_any = True
                break
        if not intersects_any:
            raise QgsProcessingException(
                "The selected polygon does not intersect any of the working extents."
            )

        feedback.pushInfo(
            f"✓ Target feature found: FID={target_feature.id()}, "
            f"area={target_geom.area():.6f}"
        )

        # ── Steps 2-4b: Process extents and aggregate gaps ───────────────────
        all_adjacent_gaps = QgsGeometry()
        total_gap_area = 0.0

        for idx, ext_geom in enumerate(extent_geoms):
            if feedback.isCanceled():
                return {}

            feedback.setProgressText(f"Step 2-4/5: Processing extent {idx+1}/{len(extent_geoms)}...")
            feedback.setProgress(20 + int(60 * idx / len(extent_geoms)))

            ext_rect = ext_geom.boundingBox()

            # Step 2: Collect all features within this extent's bounding box
            all_original_geoms = []
            request = QgsFeatureRequest().setFilterRect(ext_rect).setNoAttributes()
            feat_count = 0
            for feat in layer.getFeatures(request):
                if feedback.isCanceled():
                    return {}
                geom = feat.geometry()
                if geom.isEmpty():
                    continue
                # Use ORIGINAL geometry (no clipping) to preserve exact boundaries.
                all_original_geoms.append(geom)
                feat_count += 1

            if not all_original_geoms:
                continue

            # Step 3: Compute gaps
            all_union = QgsGeometry.unaryUnion(all_original_geoms)
            if all_union.isEmpty():
                continue
            if not all_union.isGeosValid():
                all_union = all_union.makeValid()

            # Gap = extent geometry minus union of all features
            raw_gap = ext_geom.difference(all_union)
            if raw_gap.isEmpty() or raw_gap.area() <= 0:
                continue

            # Filter out edge gaps using the boundary of ext_geom
            ext_boundary = QgsGeometry(ext_geom.constGet().boundary())
            gap_parts = (
                raw_gap.asGeometryCollection()
                if raw_gap.isMultipart()
                else [raw_gap]
            )
            internal_parts = []
            for part in gap_parts:
                if part.isEmpty() or part.area() <= 0:
                    continue
                if not part.intersects(ext_boundary):
                    internal_parts.append(part)

            if not internal_parts:
                continue

            gap_geom = internal_parts[0]
            for p in internal_parts[1:]:
                gap_geom = gap_geom.combine(p)

            # Step 4: Filter adjacent gaps
            adjacent_gaps = QgsGeometry()
            target_clipped = target_geom.intersection(ext_geom)
            if target_clipped.isEmpty():
                continue

            gap_parts = (
                gap_geom.asGeometryCollection()
                if gap_geom.isMultipart()
                else [gap_geom]
            )
            for part in gap_parts:
                if part.isEmpty() or part.area() <= 0:
                    continue
                if part.touches(target_clipped) or part.intersects(target_clipped):
                    if adjacent_gaps.isEmpty():
                        adjacent_gaps = QgsGeometry(part)
                    else:
                        adjacent_gaps = adjacent_gaps.combine(part)

            if adjacent_gaps.isEmpty():
                continue

            # Step 4b: Clean gap to prevent overlaps
            adjacent_gaps = adjacent_gaps.difference(target_geom)
            if adjacent_gaps.isEmpty() or adjacent_gaps.area() <= 0:
                continue

            gap_bbox = adjacent_gaps.boundingBox()
            request = QgsFeatureRequest().setFilterRect(ext_rect).setNoAttributes()
            for feat in layer.getFeatures(request):
                if feedback.isCanceled():
                    return {}
                if feat.id() == target_feature.id():
                    continue
                neighbor_geom = feat.geometry()
                if neighbor_geom.isEmpty():
                    continue
                if gap_bbox.intersects(neighbor_geom.boundingBox()):
                    if adjacent_gaps.intersects(neighbor_geom):
                        adjacent_gaps = adjacent_gaps.difference(neighbor_geom)
                        if adjacent_gaps.isEmpty() or adjacent_gaps.area() <= 0:
                            break
                        gap_bbox = adjacent_gaps.boundingBox()

            if not adjacent_gaps.isEmpty() and adjacent_gaps.area() > 0:
                if all_adjacent_gaps.isEmpty():
                    all_adjacent_gaps = QgsGeometry(adjacent_gaps)
                else:
                    all_adjacent_gaps = all_adjacent_gaps.combine(adjacent_gaps)
                total_gap_area += adjacent_gaps.area()

        # ── Step 5: Compute new geometry ─────────────────────────────────────
        feedback.setProgressText("Step 5/5: Building result geometry...")
        feedback.setProgress(80)

        if not all_adjacent_gaps.isEmpty():
            parts = []
            # Gather original target parts
            if target_geom.isMultipart():
                for p in target_geom.asGeometryCollection():
                    if not p.isEmpty() and p.area() > 0:
                        parts.append(QgsGeometry(p))
            else:
                parts.append(QgsGeometry(target_geom))
            # Gather gap parts
            if all_adjacent_gaps.isMultipart():
                for p in all_adjacent_gaps.asGeometryCollection():
                    if not p.isEmpty() and p.area() > 0:
                        parts.append(QgsGeometry(p))
            else:
                parts.append(QgsGeometry(all_adjacent_gaps))

            new_geom = None
            # Try to snap and merge target and gap cleanly into a single polygon
            try:
                snapped_gap = QgsGeometrySnapper.snapGeometry(
                    all_adjacent_gaps, 1e-5, [target_geom], QgsGeometrySnapper.PreferNodes
                )
                if not snapped_gap.isEmpty() and snapped_gap.area() > 0:
                    merged = target_geom.combine(snapped_gap)
                    if not merged.isEmpty() and merged.isGeosValid():
                        new_geom = merged
                        feedback.pushInfo("✓ Successfully snapped and merged target and gap geometries into a single polygon.")
            except Exception as e:
                feedback.pushInfo(f"ℹ Snapper merge failed: {e}. Falling back to MultiPolygon collection.")

            # Safe fallback: construct MultiPolygon with separate parts
            if new_geom is None:
                new_geom = QgsGeometry.collectGeometry(parts)

            original_area = target_geom.area()
            feedback.pushInfo(
                f"✓ Result geometry (MultiPolygon with {len(parts)} parts):\n"
                f"  Original area : {original_area:.6f}\n"
                f"  Gaps filled   : {total_gap_area:.6f}\n"
                f"  Total area    : {new_geom.area():.6f}"
            )
        else:
            new_geom = QgsGeometry(target_geom)
            feedback.pushInfo("ℹ No adjacent gaps. Polygon unchanged.")

        # ── Create preview output ────────────────────────────────────────────
        preview_fields = QgsFields()
        preview_fields.append(QgsField('role', QVariant.String))
        preview_fields.append(QgsField('fid_ref', QVariant.LongLong))
        preview_fields.append(QgsField('area', QVariant.Double))
        preview_fields.append(QgsField('description', QVariant.String))

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT_PREVIEW, context,
            preview_fields, QgsWkbTypes.MultiPolygon, layer.crs(),
        )
        if sink is None:
            raise QgsProcessingException("Could not create preview output.")

        self.preview_layer_id = dest_id

        # Add features in drawing order: bottom to top
        # -- 1. Result polygon (drawn first/at the bottom)
        f_res = QgsFeature(preview_fields)
        geom_res = QgsGeometry(new_geom)
        geom_res.convertToMultiType()
        f_res.setGeometry(geom_res)
        f_res.setAttributes([
            'result',
            target_feature.id(),
            new_geom.area(),
            'Result polygon (after)',
        ])
        sink.addFeature(f_res)

        # -- 2. Original polygon (drawn in the middle, transparent fill with outline)
        f_orig = QgsFeature(preview_fields)
        geom_orig = QgsGeometry(target_geom)
        geom_orig.convertToMultiType()
        f_orig.setGeometry(geom_orig)
        f_orig.setAttributes([
            'original',
            target_feature.id(),
            target_geom.area(),
            'Original polygon (before)',
        ])
        sink.addFeature(f_orig)

        # -- 3. Gap fill area (drawn on top)
        if not all_adjacent_gaps.isEmpty():
            f_gap = QgsFeature(preview_fields)
            geom_gap = QgsGeometry(all_adjacent_gaps)
            geom_gap.convertToMultiType()
            f_gap.setGeometry(geom_gap)
            f_gap.setAttributes([
                'gap_fill',
                target_feature.id(),
                total_gap_area,
                'Gap area to be filled',
            ])
            sink.addFeature(f_gap)

        # ── Apply changes (if requested) ─────────────────────────────────────
        if apply_changes and not all_adjacent_gaps.isEmpty():
            feedback.pushInfo("\n━━━ Applying changes to source layer ━━━")

            if not layer.isEditable():
                if not layer.startEditing():
                    raise QgsProcessingException(
                        "Cannot start editing on the layer. "
                        "Check that the data source is writable."
                    )

            layer.beginEditCommand("Fill Polygon Gaps")
            try:
                success = layer.changeGeometry(target_feature.id(), new_geom)
                if not success:
                    layer.destroyEditCommand()
                    raise QgsProcessingException(
                        "Failed to update geometry. The feature may have been "
                        "deleted or the layer is locked."
                    )
                layer.endEditCommand()
                feedback.pushInfo(
                    "✓ Changes applied. Use Edit > Undo (Ctrl+Z) to revert.\n"
                    "  Remember to save edits when satisfied."
                )
            except QgsProcessingException:
                raise
            except Exception as e:
                layer.destroyEditCommand()
                raise QgsProcessingException(
                    f"Error applying changes: {str(e)}"
                )
        elif apply_changes and all_adjacent_gaps.isEmpty():
            feedback.pushInfo("\nℹ No gaps to fill — no changes applied.")
        else:
            feedback.pushInfo(
                "\n━━━ Preview Only ━━━\n"
                "Inspect the 'Preview Output' layer:\n"
                "  • Blue outline = original polygon boundary\n"
                "  • Red fill     = gap area to be filled\n"
                "  • Green fill   = result polygon\n\n"
                "If satisfied, re-run with 'Apply changes' checked."
            )

        feedback.setProgress(100)
        return {self.OUTPUT_PREVIEW: dest_id}

    # =========================================================================
    #  POST-PROCESSING: Auto-style the preview layer
    # =========================================================================

    def postProcessAlgorithm(self, context, feedback):
        """Apply categorized style to the single preview layer with outlines for original target."""
        try:
            if hasattr(self, 'preview_layer_id') and self.preview_layer_id:
                lyr_preview = QgsProcessingUtils.mapLayerFromString(self.preview_layer_id, context)
                if lyr_preview:
                    # 1. Original (outline blue, transparent fill)
                    sym_orig = QgsSymbol.defaultSymbol(QgsWkbTypes.PolygonGeometry)
                    sym_orig.setColor(QColor(0, 0, 0, 0))  # transparent fill
                    sym_orig.symbolLayer(0).setFillColor(QColor(0, 0, 0, 0))
                    sym_orig.symbolLayer(0).setStrokeColor(QColor(52, 152, 219))  # Blue
                    sym_orig.symbolLayer(0).setStrokeWidth(1.5)

                    # 2. Gap Fill (semi-transparent red fill)
                    sym_gap = QgsSymbol.defaultSymbol(QgsWkbTypes.PolygonGeometry)
                    sym_gap.setColor(QColor(231, 76, 60, 100))  # Red (semi-transparent)
                    sym_gap.symbolLayer(0).setFillColor(QColor(231, 76, 60, 100))
                    sym_gap.symbolLayer(0).setStrokeColor(QColor(192, 57, 43))
                    sym_gap.symbolLayer(0).setStrokeWidth(0.5)

                    # 3. Result (semi-transparent green fill)
                    sym_res = QgsSymbol.defaultSymbol(QgsWkbTypes.PolygonGeometry)
                    sym_res.setColor(QColor(46, 204, 113, 100))  # Green (semi-transparent)
                    sym_res.symbolLayer(0).setFillColor(QColor(46, 204, 113, 100))
                    sym_res.symbolLayer(0).setStrokeColor(QColor(39, 174, 96))
                    sym_res.symbolLayer(0).setStrokeWidth(0.5)

                    categories = [
                        QgsRendererCategory('original', sym_orig, 'Original Target'),
                        QgsRendererCategory('gap_fill', sym_gap, 'Gap Filled'),
                        QgsRendererCategory('result', sym_res, 'Final Result')
                    ]

                    renderer = QgsCategorizedSymbolRenderer('role', categories)
                    lyr_preview.setRenderer(renderer)
                    lyr_preview.triggerRepaint()
        except Exception as e:
            feedback.pushInfo(f"Note: Could not auto-style preview layer: {e}")

        return {}

    # =========================================================================
    #  HELPER METHODS
    # =========================================================================

    def _find_target_feature(
        self, layer, extent_rect, label_field, feature_value, feedback
    ):
        """
        Locate the target feature by field value or FID.
        
        If label_field is provided, searches features within the extent
        for a matching field value. Otherwise, looks up by FID.
        
        Returns:
            QgsFeature: The matched feature.
        Raises:
            QgsProcessingException: If no matching feature is found.
        """
        if label_field:
            # ── Search by field value ────────────────────────────────────
            field_idx = layer.fields().indexOf(label_field)
            if field_idx < 0:
                raise QgsProcessingException(
                    f"Field '{label_field}' not found in layer '{layer.name()}'.\n"
                    f"Available fields: {', '.join(f.name() for f in layer.fields())}"
                )

            request = QgsFeatureRequest()
            if extent_rect and not extent_rect.isEmpty():
                request.setFilterRect(extent_rect)
            candidates = []

            for feat in layer.getFeatures(request):
                val = str(feat[label_field]).strip()
                if val == feature_value:
                    return feat
                candidates.append(val)

            # Not found — provide helpful message
            if candidates:
                unique = sorted(set(candidates))[:20]
                hint = ', '.join(f"'{v}'" for v in unique)
                raise QgsProcessingException(
                    f"No feature with {label_field}='{feature_value}' "
                    f"found in the extent.\n"
                    f"Available values (up to 20): {hint}"
                )
            else:
                raise QgsProcessingException(
                    f"No features found within the extent to search."
                )
        else:
            # ── Search by FID ────────────────────────────────────────────
            try:
                fid = int(feature_value)
            except ValueError:
                raise QgsProcessingException(
                    f"'{feature_value}' is not a valid FID number.\n"
                    f"Either enter a numeric FID, or select a label field "
                    f"from the dropdown above."
                )

            target = layer.getFeature(fid)
            if not target.isValid() or target.geometry().isEmpty():
                # List available FIDs in extent for guidance
                request = QgsFeatureRequest()
                if extent_rect and not extent_rect.isEmpty():
                    request.setFilterRect(extent_rect)
                available = [
                    str(f.id()) for f in layer.getFeatures(request)
                ][:20]
                raise QgsProcessingException(
                    f"No valid feature with FID={fid}.\n"
                    f"FIDs in extent (up to 20): {', '.join(available)}"
                )

            return target
